vim.g.colors_name = "yodovim"

local bg = "#000000"
local fg = "#ffffff"

local function set(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

local groups = {
  Normal = { fg = fg, bg = bg },
  NormalFloat = { fg = fg, bg = bg },
  NormalNC = { fg = fg, bg = bg },
  EndOfBuffer = { fg = bg },
  ColorColumn = { bg = bg },

  Cursor = { fg = bg, bg = fg },
  CursorLine = { underline = true },
  CursorLineNr = { fg = fg, bold = true },
  LineNr = { fg = fg },
  SignColumn = { fg = fg, bg = bg },
  FoldColumn = { fg = fg, bg = bg },
  Folded = { italic = true },
  Conceal = { fg = fg },
  VertSplit = { fg = fg, bg = bg },
  WinSeparator = { fg = fg, bg = bg },
  WinBar = { fg = fg, bg = bg },
  WinBarNC = { fg = fg, bg = bg },

  Visual = { fg = bg, bg = fg },
  VisualNOS = { fg = bg, bg = fg },
  Search = { fg = bg, bg = fg },
  IncSearch = { fg = bg, bg = fg, bold = true },
  CurSearch = { fg = bg, bg = fg, bold = true },
  MatchParen = { fg = bg, bg = fg, bold = true },

  StatusLine = { fg = bg, bg = fg },
  StatusLineNC = { fg = fg, bg = bg },
  TabLine = { fg = fg, bg = bg },
  TabLineSel = { fg = bg, bg = fg, bold = true },
  TabLineFill = { fg = fg, bg = bg },
  Title = { bold = true },
  Directory = { bold = true },

  Pmenu = { fg = bg, bg = fg },
  PmenuSel = { fg = fg, bg = bg },
  PmenuKind = { fg = bg, bg = fg },
  PmenuKindSel = { fg = fg, bg = bg },
  PmenuExtra = { fg = bg, bg = fg },
  PmenuExtraSel = { fg = fg, bg = bg },
  PmenuSbar = { bg = fg },
  PmenuThumb = { bg = bg },

  FloatBorder = { fg = fg, bg = bg },
  FloatTitle = { fg = fg, bg = bg, bold = true },
  FloatFooter = { fg = fg, bg = bg },

  QuickFixLine = { fg = bg, bg = fg, bold = true },
  WildMenu = { fg = bg, bg = fg },
  MoreMsg = { bold = true },
  ModeMsg = { bold = true },
  Question = { bold = true },
  WarningMsg = { bold = true, underline = true },
  ErrorMsg = { bold = true, underline = true },

  Comment = { italic = true },
  Keyword = { bold = true },
  Statement = { bold = true },
  Conditional = { bold = true },
  Repeat = { bold = true },
  Label = { bold = true },
  Exception = { bold = true },
  Operator = {},
  Function = { underline = true },
  Method = { underline = true },
  Identifier = {},
  Constant = { bold = true },
  String = {},
  Character = {},
  Number = { bold = true },
  Boolean = { bold = true },
  Float = { bold = true },
  Type = { bold = true, italic = true },
  Structure = { bold = true },
  Typedef = { bold = true, italic = true },
  PreProc = { bold = true },
  Include = { bold = true },
  Define = { bold = true },
  Macro = { bold = true },
  PreCondit = { bold = true },
  Special = {},
  SpecialChar = {},
  Tag = { bold = true },
  Delimiter = {},
  SpecialComment = { italic = true },
  Debug = {},
  Underlined = { underline = true },
  Ignore = {},
  Error = { bold = true, underline = true },
  Todo = { fg = bg, bg = fg, bold = true },

  SpecialKey = { fg = fg },
  NonText = { fg = fg },
  Whitespace = { fg = fg },
  SpellBad = { underline = true },
  SpellCap = { underline = true },
  SpellLocal = { underline = true },
  SpellRare = { underline = true },

  DiffAdd = { fg = bg, bg = fg },
  DiffChange = { italic = true },
  DiffDelete = { strikethrough = true },
  DiffText = { bold = true },
  DiffAdded = { fg = bg, bg = fg },
  DiffRemoved = { strikethrough = true },

  DiagnosticError = { bold = true, underline = true },
  DiagnosticWarn = { italic = true, underline = true },
  DiagnosticInfo = { underline = true },
  DiagnosticHint = { underline = true },
  DiagnosticOk = {},
  DiagnosticUnnecessary = { italic = true },
  DiagnosticUnderlineError = { underline = true },
  DiagnosticUnderlineWarn = { underline = true },
  DiagnosticUnderlineInfo = { underline = true },
  DiagnosticUnderlineHint = { underline = true },
  DiagnosticSignError = { bold = true },
  DiagnosticSignWarn = { italic = true },
  DiagnosticSignInfo = {},
  DiagnosticSignHint = {},
  DiagnosticVirtualTextError = { bold = true },
  DiagnosticVirtualTextWarn = { italic = true },
  DiagnosticVirtualTextInfo = {},
  DiagnosticVirtualTextHint = {},
  DiagnosticFloatingError = { bold = true },
  DiagnosticFloatingWarn = { italic = true },
  DiagnosticFloatingInfo = {},
  DiagnosticFloatingHint = {},

  LspReferenceText = { underline = true },
  LspReferenceWrite = { underline = true },
  LspReferenceRead = { underline = true },
  LspInlayHint = { italic = true },
  LspCodeLens = { italic = true },
  LspSignatureActiveParameter = { fg = bg, bg = fg },

  GitSignsAdd = { bold = true },
  GitSignsChange = { italic = true },
  GitSignsDelete = { strikethrough = true },
  GitSignsAddLn = { bold = true },
  GitSignsChangeLn = { italic = true },
  GitSignsDeleteLn = { strikethrough = true },
  GitSignsAddNr = { bold = true },
  GitSignsChangeNr = { italic = true },
  GitSignsDeleteNr = { strikethrough = true },

  NeoTreeNormal = { fg = fg, bg = bg },
  NeoTreeNormalNC = { fg = fg, bg = bg },
  NeoTreeCursorLine = { underline = true },
  NeoTreeDirectoryName = { bold = true },
  NeoTreeFileName = {},
  NeoTreeFileIcon = {},
  NeoTreeRootName = { bold = true },
  NeoTreeTitleBar = { bold = true },
  NeoTreeGitAdded = { bold = true },
  NeoTreeGitModified = { italic = true },
  NeoTreeGitDeleted = { strikethrough = true },
  NeoTreeGitUntracked = {},
  NeoTreeIndentMarker = {},
  NeoTreeExpander = { bold = true },
  NeoTreeFloatBorder = { fg = fg },
  NeoTreeFloatTitle = { bold = true },

  BufferLineFill = { fg = fg, bg = bg },
  BufferLineBuffer = { fg = fg, bg = bg },
  BufferLineBufferVisible = { fg = fg, bg = bg },
  BufferLineBufferSelected = { fg = bg, bg = fg, bold = true },
  BufferLineModified = { italic = true },
  BufferLineModifiedVisible = { italic = true },
  BufferLineModifiedSelected = { fg = bg, bg = fg, bold = true },
  BufferLineCloseButton = {},
  BufferLineCloseButtonVisible = {},
  BufferLineCloseButtonSelected = { fg = bg, bg = fg },
  BufferLineIndicatorSelected = { fg = fg },
  BufferLineSeparator = { fg = fg, bg = bg },
  BufferLineSeparatorVisible = { fg = fg, bg = bg },
  BufferLineSeparatorSelected = { fg = fg, bg = bg },
  BufferLineTab = { fg = fg, bg = bg },
  BufferLineTabSelected = { fg = bg, bg = fg, bold = true },
  BufferLineTabClose = {},
  BufferLineTabSeparator = {},
  BufferLineTabSeparatorSelected = {},
  BufferLineDuplicate = {},
  BufferLineDuplicateVisible = {},
  BufferLineDuplicateSelected = { fg = bg, bg = fg },
  BufferLineDiagnostic = {},
  BufferLineDiagnosticVisible = {},
  BufferLineDiagnosticSelected = { fg = bg, bg = fg },
  BufferLineDiagnosticError = { bold = true },
  BufferLineDiagnosticWarn = { italic = true },
  BufferLineDiagnosticInfo = {},
  BufferLineDiagnosticHint = {},

  TelescopeNormal = { fg = fg, bg = bg },
  TelescopeBorder = { fg = fg, bg = bg },
  TelescopePromptBorder = { fg = fg, bg = bg },
  TelescopePromptNormal = { fg = fg, bg = bg },
  TelescopePromptPrefix = { fg = bg, bg = fg, bold = true },
  TelescopePromptTitle = { fg = bg, bg = fg, bold = true },
  TelescopePreviewTitle = { fg = bg, bg = fg, bold = true },
  TelescopeResultsTitle = { fg = bg, bg = fg, bold = true },
  TelescopeSelection = { fg = bg, bg = fg },
  TelescopeSelectionCaret = { fg = bg, bg = fg, bold = true },
  TelescopeMatching = { bold = true },
  TelescopeResultsDiffAdd = { bold = true },
  TelescopeResultsDiffChange = { italic = true },
  TelescopeResultsDiffDelete = { strikethrough = true },

  WhichKey = { bold = true },
  WhichKeyGroup = { bold = true, underline = true },
  WhichKeyDesc = {},
  WhichKeySeparator = {},
  WhichKeyFloat = { bg = bg },

  FlashLabel = { fg = bg, bg = fg, bold = true },
  FlashMatch = { fg = bg, bg = fg },
  FlashCurrent = { fg = bg, bg = fg, bold = true },

  IlluminatedWordText = { underline = true },
  IlluminatedWordRead = { underline = true },
  IlluminatedWordWrite = { underline = true },

  IblIndent = { fg = fg },
  IblScope = { fg = fg },

  AlphaHeader = { fg = fg, bold = true },
  AlphaHeaderLabel = { fg = fg, bold = true },
  AlphaButtons = { fg = fg },
  AlphaShortcut = { fg = bg, bg = fg, bold = true },
  AlphaFooter = { italic = true },

  BlinkCmpKind = {},
  BlinkCmpDoc = { bg = bg },
  BlinkCmpDocBorder = { fg = fg },
  BlinkCmpDocSeparator = {},
  BlinkCmpMenu = { fg = bg, bg = fg },
  BlinkCmpMenuBorder = { fg = fg },
  BlinkCmpMenuSelection = { fg = fg, bg = bg },
  BlinkCmpScrollBarThumb = { bg = bg },
  BlinkCmpScrollBarGutter = { bg = fg },

  LazyButton = { fg = bg, bg = fg },
  LazyButtonActive = { fg = fg, bg = bg, bold = true },
  LazyProgressDone = { bold = true },
  LazyProgressTodo = {},
  LazyReasonPlugin = {},
  LazyReasonStart = { bold = true },
  LazyReasonKeys = { italic = true },
  LazyReasonCmd = {},
  LazyReasonEvent = {},
  LazyReasonFt = {},
  LazyReasonImport = {},
  LazyReasonSource = {},
  LazyReasonRuntime = {},
  LazyReasonConfig = {},
  LazyDirectory = { bold = true },
  LazyValue = {},
  LazySpecial = { bold = true },
  LazyCommit = { italic = true },
  LazyCommitType = { bold = true },
  LazyHunk = {},

  HealthError = { bold = true, underline = true },
  HealthWarn = { italic = true, underline = true },
  HealthSuccess = { bold = true },

  Terminal = { fg = fg, bg = bg },
  MsgArea = { fg = fg },
  MsgSeparator = {},

  htmlLink = { underline = true },
  htmlBold = { bold = true },
  htmlItalic = { italic = true },
  markdownBold = { bold = true },
  markdownItalic = { italic = true },
  markdownH1 = { bold = true },
  markdownH2 = { bold = true },
  markdownH3 = { bold = true },
  markdownH4 = { bold = true },
  markdownH5 = { bold = true },
  markdownH6 = { bold = true },
  markdownCode = { fg = fg },
  markdownCodeBlock = { fg = fg },
  markdownLinkText = { underline = true },
  markdownUrl = { underline = true },
  markdownListMarker = { bold = true },
  markdownRule = { bold = true },

  gitcommitSummary = { bold = true },
  gitcommitHeader = { bold = true },
  gitcommitSelectedFile = { bold = true },
}

for name, opts in pairs(groups) do
  set(name, opts)
end